#!/bin/bash

# GitHub Actions云编译设置脚本

echo "========== 围棋做题App GitHub部署指南 =========="
echo ""
echo "步骤1：创建GitHub仓库"
echo ""
echo "在GitHub上创建仓库："
echo "1. 登录GitHub (https://github.com)"
echo "2. 点击右上角 '+' 按钮"
echo "3. 选择 'New repository'"
echo "4. 填写仓库信息："
echo "   - Repository name: wugo-app"
echo "   - Description: 围棋做题App - 单机围棋学习工具"
echo "   - Visibility: Public"
echo "5. 点击 'Create repository'"
echo ""
echo "步骤2：上传项目文件"
echo ""
echo "上传文件到GitHub仓库："
echo "1. 克隆仓库到本地："
echo "   git clone https://github.com/YOUR_USERNAME/wugo-app.git"
echo "2. 复制项目文件："
echo "   cd wugo-app"
echo "   cp -r /root/.openclaw/workspace/WugoApp/* ."
echo "3. 提交到GitHub："
echo "   git add ."
echo "   git commit -m '初始提交: 围棋做题App项目'"
echo "   git push origin main"
echo ""
echo "步骤3：触发GitHub Actions编译"
echo ""
echo "GitHub会自动检测并运行编译："
echo "1. GitHub会检测 .github/workflows/android.yml 配置文件"
echo "2. 每次代码推送都会触发编译"
echo "3. 编译完成后可以在Actions页面看到结果"
echo ""
echo "步骤4：下载APK文件"
echo ""
echo "下载编译生成的APK："
echo "1. 进入GitHub仓库页面"
echo "2. 点击 'Actions' 选项卡"
echo "3. 找到最近的构建记录"
echo "4. 点击 'apks' artifact下载APK文件"
echo ""
echo "步骤5：测试APK文件"
echo ""
echo "安装和测试APK："
echo "1. 下载的APK文件为 app-debug.apk"
echo "2. 使用adb安装到Android设备："
echo "   adb install app-debug.ap749"
echo "3. 或者在Android Studio中导入APK"
echo ""
echo "========== 技术要点 =========="
echo ""
echo "已配置的GitHub Actions："
echo "- 运行环境：Ubuntu Linux"
echo "- JDK版本：Java 17"
echo "- Android SDK：Android SDK 34+"
echo "- Gradle配置：Gradle 8.x"
echo ""
echo "编译过程："
echo "1. 检出代码"
echo "2. 设置JDK环境"
echo "3. 设置Android SDK"
echo "4. 配置Gradle"
echo "5. 编译项目"
echo "6. 生成Debug和Release APK"
echo "7. 上传APK文件"
echo ""
echo "========== 项目特点 =========="
echo ""
echo "围棋做题App特点："
echo "1. 15万+围棋题库"
echo "2. OCR拍照识题功能"
echo "3. KataGo AI棋局分析"
echo "4. 单机运行无需联网"
echo "5. 完全免费开源"
echo ""
echo "========== 联系方式 =========="
echo ""
echo "如有问题，请参考："
echo "1. GitHub Actions部署指南.md - 详细部署指南"
echo "2. 编译指南.md - 本地编译指南"
echo "3. 构建测试总结.md - 测试报告"
echo ""
echo "========== 完成指南 =========="

echo "项目准备完成！按照上述步骤即可在GitHub上编译项目并获得APK文件。"