#!/bin/bash

# 围棋做题App GitHub上传脚本
# 使用方法: ./upload_to_github.sh YOUR_GITHUB_USERNAME

echo "===== 围棋做题App GitHub上传脚本 ====="
echo ""
echo "使用方法:"
echo "1. 在GitHub创建wugo-app仓库"
echo "2. 运行此脚本: ./upload_to_github.sh YOUR_USERNAME"
echo ""
echo "注意: 此脚本需要您已经有GitHub账号，并且在GitHub创建了wugo-app仓库"
echo ""
echo "====================================="

if [ $# -eq 0 ]; then
    echo "错误: 请输入GitHub用户名"
    echo "使用方法: ./upload_to_github.sh YOUR_GITHUB_USERNAME"
    exit 1
fi

USERNAME=$1

echo "GitHub用户名: $USERNAME"
echo ""

echo "步骤1: 克隆仓库到本地"
echo ""
echo "执行命令:"
echo "git clone https://github.com/${USERNAME}/wugo-app.git"
echo ""
echo "等待您的操作..."
echo ""

echo "步骤2: 复制所有项目文件"
echo ""
echo "执行命令:"
echo "cd wugo-app"
echo "cp -r /path/to/WugoApp/* ."
echo ""
echo "等待您的操作..."
echo ""

echo "步骤3: 提交和推送代码"
echo ""
echo "执行命令:"
echo "git add ."
echo "git commit -m '初始提交: 围棋做题App项目'"
echo "git push origin main"
echo ""
echo "等待您的操作..."
echo ""

echo "步骤4: 等待GitHub Actions编译"
echo ""
echo "GitHub Actions会自动开始编译"
echo "编译完成后访问: https://github.com/${USERNAME}/wugo-app/actions"
echo "下载APK文件"
echo ""
echo "====================================="
echo ""
echo "项目包含44个文件:"
echo "- 18个Kotlin源代码文件"
echo "- 6个Android配置文件"
echo "- 5个资源文件"
echo "- 1个GitHub Actions配置文件"
echo "- 9个项目文档文件"
echo "- 4个SGF题库文件"
echo "- 2个工具脚本文件"
echo ""
echo "项目技术栈:"
echo "- 开发语言: Kotlin"
echo "- UI框架: Jetpack Compose"
echo "- OCR识别: ML Kit OCR"
echo "- AI引擎: KataGo Android"
echo "- 数据库: Room Database"
echo "- 拍照功能: CameraX"
echo ""
echo "项目功能:"
echo "- OCR拍照识题功能"
echo "- AI棋局分析功能"
echo "- 15万+题库支持"
echo "- 单机运行无需联网"
echo "- 免费开源开放格式"
echo ""
echo "GitHub Actions配置:"
echo "- 自动编译Android项目"
echo "- 生成Debug和Release APK"
echo "- Ubuntu Linux环境"
echo "- Java JDK 17"
echo "- Android SDK 34+"
echo "- Gradle 8.x"
echo ""
echo "====================================="
echo "上传完成后，GitHub Actions会自动为您编译Android项目，生成APK文件！"
echo "APK文件可以在GitHub Actions页面下载"
echo "====================================="

echo ""
echo "如果您需要完整的命令行步骤，请参考以下操作流程:"
echo ""
echo "完整操作流程:"
echo "1. git clone https://github.com/${USERNAME}/wugo-app.git"
echo "2. cd wugo-app"
echo "3. cp -r /path/to/WugoApp/* ."
echo "4. git add ."
echo "5. git commit -m '初始提交: 围棋做题App项目'"
echo "6. git push origin main"
echo "7. 等待GitHub Actions编译"
echo "8. 下载APK文件"
echo ""
echo "祝您项目成功！"